version: "3.7"

services:
  db:
    container_name: cfi
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: cfi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - cfi_postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
volumes:
  cfi_postgres:

